name: Send security alerts to slack
on:
  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:

  # Temp so we can test the workflow
  pull_request:
    branches: main

jobs:
  send_security_alerts:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Send security alert notifications to slack
        uses: kunalnagarco/action-cve@v1.8.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          slack_webhook: ${{ secrets.SECURITY_ALERTS_SLACK_WEBHOOK_URL }}
