on:
  push:
    branches:
      - main

name: release-please

env:
  ACTION_NAME: login

jobs:
  release-please-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed to tag repo and create releases
      pull-requests: write # Needed to add comments to pull requests on release
    steps:
      - uses: googleapis/release-please-action@v3
        id: release
        with:
          package-name: ${{env.ACTION_NAME}}
          release-type: node
          token: ${{ secrets.GITHUB_TOKEN }}
          command: github-release

      - uses: actions/checkout@v3
        if: ${{ steps.release.outputs.release_created }}

      - name: Tag minor version
        if: ${{ steps.release.outputs.release_created }}
        uses: richardsimko/update-tag@v1
        with:
          tag_name: v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag major version
        if: ${{ steps.release.outputs.release_created }}
        uses: richardsimko/update-tag@v1
        with:
          tag_name: v${{ steps.release.outputs.major }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release-please-pr:
    runs-on: ubuntu-latest
    needs:
      - release-please-release
    steps:
      - id: release-pr
        uses: googleapis/release-please-action@v3
        with:
          token: ${{ secrets.CHANGESETS_GITHUB_TOKEN }}
          release-type: node
          package-name: ${{env.ACTION_NAME}}
          command: release-pr
