name: Add changeset to renovate created PRs

on:
  pull_request:
    branches: [main]

jobs:
  add_changeset:
    runs-on: ubuntu-latest
    name: Add changeset
    permissions:
      contents: write
    steps:
      - name: checkout
        uses: actions/checkout@v3.3.0
        with:
          fetch-depth: 0

      - name: Add renovate changeset
        id: add_renovate_changeset
        uses: OctopusDeploy/util-actions/add-changeset@add-changeset.0.2.0
        with:
          type: patch
          summary: ${{ github.event.pull_request.title }}
          ignore: |
            **/node_modules/**/*

      - name: Print changeset contents
        run: cat ${{ steps.add_renovate_changeset.outputs.changesetPath }}

      - name: Commit & Push changes
        uses: actions-js/push@v1.4
        with:
          branch: ${{ github.head_ref }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
